import {
  SecurityEventCategory,
  SecuritySeverity,
  PlatformSecurityRuleDTO,
  SecurityRuleUpdateDTO,
  SecurityRuleSuppressDTO,
} from '@pixmatch/types';
import { prisma } from '@pixmatch/database';

export interface BuiltinRuleDefinition {
  rule_id: string;
  name: string;
  description: string;
  category: SecurityEventCategory;
  severity: SecuritySeverity;
  threshold: number;
  window_seconds: number;
  cooldown_seconds: number;
  action: string;
}

export const BUILTIN_SECURITY_RULES: BuiltinRuleDefinition[] = [
  {
    rule_id: 'ADMIN_BRUTE_FORCE',
    name: 'Admin Brute Force Attack Detection',
    description: 'Multiple failed administrator authentication attempts from the same IP or target account.',
    category: SecurityEventCategory.AUTHENTICATION,
    severity: SecuritySeverity.HIGH,
    threshold: 5,
    window_seconds: 300,
    cooldown_seconds: 600,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'ADMIN_MFA_FAILURE_SPIKE',
    name: 'Admin MFA Failure Spike',
    description: 'Repeated failed MFA/TOTP verification attempts on an administrator session.',
    category: SecurityEventCategory.AUTHENTICATION,
    severity: SecuritySeverity.HIGH,
    threshold: 3,
    window_seconds: 300,
    cooldown_seconds: 600,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'ADMIN_SESSION_ANOMALY',
    name: 'Admin Session Anomaly',
    description: 'Use of expired, revoked, or suspended administrator session token.',
    category: SecurityEventCategory.SESSION,
    severity: SecuritySeverity.HIGH,
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 300,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'ADMIN_PRIVILEGE_CHANGE',
    name: 'Admin Privilege Modification',
    description: 'Privilege change or role downgrade followed by unauthorized privilege invocation.',
    category: SecurityEventCategory.PRIVILEGE,
    severity: SecuritySeverity.HIGH,
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 300,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'ADMIN_SESSION_AFTER_SUSPENSION',
    name: 'Suspended Admin Activity Attempt',
    description: 'Authenticated request attempted using a session belonging to a suspended administrator.',
    category: SecurityEventCategory.SESSION,
    severity: SecuritySeverity.CRITICAL,
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 300,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'ADMIN_PASSWORD_RESET_SPIKE',
    name: 'Admin Password Reset Spike',
    description: 'Rapid repeated password reset requests targeted at administrative accounts.',
    category: SecurityEventCategory.AUTHENTICATION,
    severity: SecuritySeverity.MEDIUM,
    threshold: 4,
    window_seconds: 600,
    cooldown_seconds: 900,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'MULTIPLE_FAILED_LOGINS',
    name: 'Studio/User Authentication Failure Burst',
    description: 'Burst of failed login attempts across studio or customer portal accounts.',
    category: SecurityEventCategory.AUTHENTICATION,
    severity: SecuritySeverity.MEDIUM,
    threshold: 10,
    window_seconds: 300,
    cooldown_seconds: 600,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'RATE_LIMIT_ABUSE',
    name: 'High Rate Limit Breach Rate',
    description: 'Sustained rate limit violations across public, client, or API endpoints.',
    category: SecurityEventCategory.RATE_LIMIT,
    severity: SecuritySeverity.MEDIUM,
    threshold: 15,
    window_seconds: 120,
    cooldown_seconds: 300,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'API_ERROR_ABUSE',
    name: 'High Frequency API Error Generation',
    description: 'Abnormal rate of 4xx/5xx errors generated by a single client or IP.',
    category: SecurityEventCategory.API_ABUSE,
    severity: SecuritySeverity.LOW,
    threshold: 30,
    window_seconds: 120,
    cooldown_seconds: 300,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'REPEATED_IDOR_DENIAL',
    name: 'Repeated Insecure Direct Object Reference (IDOR) Denials',
    description: 'Repeated attempts to access unauthorized photo, gallery, or invoice IDs.',
    category: SecurityEventCategory.AUTHORIZATION,
    severity: SecuritySeverity.HIGH,
    threshold: 3,
    window_seconds: 300,
    cooldown_seconds: 600,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'CROSS_TENANT_ACCESS_ATTEMPT',
    name: 'Cross-Tenant Access Boundary Violation',
    description: 'Explicit attempt by studio member to access another studio tenant resource.',
    category: SecurityEventCategory.TENANT_SECURITY,
    severity: SecuritySeverity.CRITICAL,
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 600,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'UNUSUAL_PUBLIC_PORTAL_ACTIVITY',
    name: 'Unusual Public Portal Activity',
    description: 'Mass probing or scraping of public gallery links and guest PINs.',
    category: SecurityEventCategory.CLIENT_PORTAL,
    severity: SecuritySeverity.MEDIUM,
    threshold: 20,
    window_seconds: 180,
    cooldown_seconds: 600,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'STORAGE_OAUTH_FAILURE_SPIKE',
    name: 'Storage OAuth Callback Failure Spike',
    description: 'High volume of OAuth connection failures with storage providers (Dropbox, Google Drive, S3).',
    category: SecurityEventCategory.STORAGE,
    severity: SecuritySeverity.MEDIUM,
    threshold: 5,
    window_seconds: 300,
    cooldown_seconds: 600,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'OAUTH_CALLBACK_REPLAY',
    name: 'OAuth Callback State / Nonce Replay',
    description: 'Attempt to reuse an already exchanged OAuth authorization code or invalid state token.',
    category: SecurityEventCategory.OAUTH,
    severity: SecuritySeverity.HIGH,
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 300,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'WEBHOOK_SIGNATURE_FAILURE_SPIKE',
    name: 'Webhook Signature Verification Failures',
    description: 'Inbound webhook requests failing cryptographic HMAC signature verification.',
    category: SecurityEventCategory.WEBHOOK,
    severity: SecuritySeverity.HIGH,
    threshold: 5,
    window_seconds: 300,
    cooldown_seconds: 600,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'PAYMENT_WEBHOOK_REPLAY',
    name: 'Payment Webhook Idempotency / Replay Anomaly',
    description: 'Replayed payment gateway webhooks outside acceptable retry jitter windows.',
    category: SecurityEventCategory.PAYMENT,
    severity: SecuritySeverity.HIGH,
    threshold: 3,
    window_seconds: 300,
    cooldown_seconds: 600,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'PAYMENT_WEBHOOK_SIGNATURE_FAILURE',
    name: 'Payment Webhook Signature Mismatch',
    description: 'Cryptographic signature mismatch on Stripe, Razorpay, or payment webhooks.',
    category: SecurityEventCategory.PAYMENT,
    severity: SecuritySeverity.CRITICAL,
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 300,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'DOWNLOAD_ABUSE',
    name: 'Bulk Photo Download Abuse',
    description: 'Excessive high-volume high-resolution asset downloads breaching normal client patterns.',
    category: SecurityEventCategory.DOWNLOAD,
    severity: SecuritySeverity.MEDIUM,
    threshold: 100,
    window_seconds: 300,
    cooldown_seconds: 600,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'AI_ENDPOINT_ABUSE',
    name: 'AI Model & Embedding Inference Abuse',
    description: 'Excessive requests or malformed payloads targeting face detection and embedding pipelines.',
    category: SecurityEventCategory.AI,
    severity: SecuritySeverity.HIGH,
    threshold: 10,
    window_seconds: 120,
    cooldown_seconds: 300,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'AUTOMATION_PERMISSION_VIOLATION',
    name: 'Automation Rule Permission Boundary Violation',
    description: 'Phase 16 automation engine task attempting unpermitted system modifications.',
    category: SecurityEventCategory.AUTOMATION,
    severity: SecuritySeverity.HIGH,
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 300,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'SECURITY_SETTING_CHANGE',
    name: 'Critical Platform Security Setting Modified',
    description: 'Audit notification for updates to security policies, rate limits, or session parameters.',
    category: SecurityEventCategory.CONFIGURATION,
    severity: SecuritySeverity.MEDIUM,
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 120,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'FEATURE_FLAG_SECURITY_CHANGE',
    name: 'Security-Sensitive Feature Flag State Change',
    description: 'Toggling feature flags that govern authentication, tenant isolation, or encryption.',
    category: SecurityEventCategory.CONFIGURATION,
    severity: SecuritySeverity.MEDIUM,
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 120,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'MIGRATION_SAFETY_FAILURE',
    name: 'Database Migration / Safety Guardrail Trigger',
    description: 'Schema change or data migration failing pre-flight safety checks.',
    category: SecurityEventCategory.INFRASTRUCTURE,
    severity: SecuritySeverity.CRITICAL,
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 300,
    action: 'CREATE_ALERT',
  },
  {
    rule_id: 'SERVICE_AUTH_FAILURE',
    name: 'Internal Microservice Auth Failure',
    description: 'Service-to-service mutual authentication or JWT signature validation failure.',
    category: SecurityEventCategory.INFRASTRUCTURE,
    severity: SecuritySeverity.HIGH,
    threshold: 3,
    window_seconds: 180,
    cooldown_seconds: 300,
    action: 'CREATE_ALERT',
  },
];

export class SecurityRulesService {
  private static mockRules: Map<string, PlatformSecurityRuleDTO> = new Map();

  static async initializeRules(): Promise<void> {
    for (const ruleDef of BUILTIN_SECURITY_RULES) {
      if (!this.mockRules.has(ruleDef.rule_id)) {
        this.mockRules.set(ruleDef.rule_id, {
          id: `rule-${ruleDef.rule_id.toLowerCase()}`,
          rule_id: ruleDef.rule_id,
          name: ruleDef.name,
          description: ruleDef.description,
          category: ruleDef.category,
          severity: ruleDef.severity,
          enabled: true,
          threshold: ruleDef.threshold,
          window_seconds: ruleDef.window_seconds,
          cooldown_seconds: ruleDef.cooldown_seconds,
          action: ruleDef.action,
          trigger_count: 0,
          created_at: new Date(),
          updated_at: new Date(),
        });
      }
    }

    if (process.env.DATABASE_URL && prisma && (prisma as any).platformSecurityRule) {
      try {
        for (const ruleDef of BUILTIN_SECURITY_RULES) {
          await (prisma as any).platformSecurityRule.upsert({
            where: { rule_id: ruleDef.rule_id },
            update: {},
            create: {
              rule_id: ruleDef.rule_id,
              name: ruleDef.name,
              description: ruleDef.description,
              category: ruleDef.category,
              severity: ruleDef.severity,
              enabled: true,
              threshold: ruleDef.threshold,
              window_seconds: ruleDef.window_seconds,
              cooldown_seconds: ruleDef.cooldown_seconds,
              action: ruleDef.action,
            },
          });
        }
      } catch (e) {
        // Fallback to mock state
      }
    }
  }

  static async listRules(category?: SecurityEventCategory): Promise<PlatformSecurityRuleDTO[]> {
    await this.initializeRules();

    if (process.env.DATABASE_URL && prisma && (prisma as any).platformSecurityRule) {
      try {
        const where = category ? { category } : {};
        const records = await (prisma as any).platformSecurityRule.findMany({
          where,
          orderBy: { name: 'asc' },
        });
        if (records && records.length > 0) {
          return records.map((r: any) => this.mapToDTO(r));
        }
      } catch (e) {
        // fallback to memory
      }
    }

    let rules = Array.from(this.mockRules.values());
    if (category) {
      rules = rules.filter((r) => r.category === category);
    }
    return rules;
  }

  static async getRule(ruleId: string): Promise<PlatformSecurityRuleDTO | null> {
    await this.initializeRules();

    if (process.env.DATABASE_URL && prisma && (prisma as any).platformSecurityRule) {
      try {
        const record = await (prisma as any).platformSecurityRule.findUnique({
          where: { rule_id: ruleId },
        });
        if (record) {
          return this.mapToDTO(record);
        }
      } catch (e) {
        // fallback
      }
    }

    return this.mockRules.get(ruleId) || null;
  }

  static async updateRule(
    ruleId: string,
    updates: SecurityRuleUpdateDTO,
    _adminId?: string
  ): Promise<PlatformSecurityRuleDTO> {
    await this.initializeRules();

    const existing = await this.getRule(ruleId);
    if (!existing) {
      throw new Error(`Security rule ${ruleId} not found`);
    }

    const updated: PlatformSecurityRuleDTO = {
      ...existing,
      ...updates,
      updated_at: new Date(),
    };
    this.mockRules.set(ruleId, updated);

    if (process.env.DATABASE_URL && prisma && (prisma as any).platformSecurityRule) {
      try {
        const record = await (prisma as any).platformSecurityRule.update({
          where: { rule_id: ruleId },
          data: {
            ...updates,
            updated_at: new Date(),
          },
        });
        return this.mapToDTO(record);
      } catch (e) {
        // fallback
      }
    }

    return updated;
  }

  static async suppressRule(
    ruleId: string,
    suppression: SecurityRuleSuppressDTO
  ): Promise<PlatformSecurityRuleDTO> {
    await this.initializeRules();

    const existing = await this.getRule(ruleId);
    if (!existing) {
      throw new Error(`Security rule ${ruleId} not found`);
    }

    const updated: PlatformSecurityRuleDTO = {
      ...existing,
      suppressed_until: new Date(suppression.suppressed_until),
      suppressed_reason: suppression.suppressed_reason,
      suppressed_by: suppression.suppressed_by,
      updated_at: new Date(),
    };
    this.mockRules.set(ruleId, updated);

    if (process.env.DATABASE_URL && prisma && (prisma as any).platformSecurityRule) {
      try {
        const record = await (prisma as any).platformSecurityRule.update({
          where: { rule_id: ruleId },
          data: {
            suppressed_until: new Date(suppression.suppressed_until),
            suppressed_reason: suppression.suppressed_reason,
            suppressed_by: suppression.suppressed_by,
            updated_at: new Date(),
          },
        });
        return this.mapToDTO(record);
      } catch (e) {
        // fallback
      }
    }

    return updated;
  }

  static async unsuppressRule(ruleId: string, _adminId?: string): Promise<PlatformSecurityRuleDTO> {
    await this.initializeRules();

    const existing = await this.getRule(ruleId);
    if (!existing) {
      throw new Error(`Security rule ${ruleId} not found`);
    }

    const updated: PlatformSecurityRuleDTO = {
      ...existing,
      suppressed_until: null,
      suppressed_reason: null,
      suppressed_by: null,
      updated_at: new Date(),
    };
    this.mockRules.set(ruleId, updated);

    if (process.env.DATABASE_URL && prisma && (prisma as any).platformSecurityRule) {
      try {
        const record = await (prisma as any).platformSecurityRule.update({
          where: { rule_id: ruleId },
          data: {
            suppressed_until: null,
            suppressed_reason: null,
            suppressed_by: null,
            updated_at: new Date(),
          },
        });
        return this.mapToDTO(record);
      } catch (e) {
        // fallback
      }
    }

    return updated;
  }

  static async isRuleSuppressed(ruleId: string): Promise<boolean> {
    const rule = await this.getRule(ruleId);
    if (!rule || !rule.enabled) return true;
    if (rule.suppressed_until) {
      const now = new Date();
      if (new Date(rule.suppressed_until) > now) {
        return true;
      }
    }
    return false;
  }

  static async recordRuleTrigger(ruleId: string): Promise<void> {
    const rule = this.mockRules.get(ruleId);
    if (rule) {
      rule.trigger_count = (rule.trigger_count || 0) + 1;
      rule.last_triggered_at = new Date();
    }

    if (process.env.DATABASE_URL && prisma && (prisma as any).platformSecurityRule) {
      try {
        await (prisma as any).platformSecurityRule.update({
          where: { rule_id: ruleId },
          data: {
            trigger_count: { increment: 1 },
            last_triggered_at: new Date(),
          },
        });
      } catch (e) {
        // fallback
      }
    }
  }

  static clearMockState(): void {
    this.mockRules.clear();
  }

  private static mapToDTO(record: any): PlatformSecurityRuleDTO {
    return {
      id: record.id,
      rule_id: record.rule_id,
      name: record.name,
      description: record.description,
      category: record.category as SecurityEventCategory,
      severity: record.severity as SecuritySeverity,
      enabled: record.enabled,
      threshold: record.threshold,
      window_seconds: record.window_seconds,
      cooldown_seconds: record.cooldown_seconds,
      action: record.action,
      suppressed_until: record.suppressed_until,
      suppressed_reason: record.suppressed_reason,
      suppressed_by: record.suppressed_by,
      last_triggered_at: record.last_triggered_at,
      trigger_count: record.trigger_count,
      created_at: record.created_at,
      updated_at: record.updated_at,
    };
  }
}
